# version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    image: ${DOCKER_USER}/${IMAGE_NAME1}:latest
    container_name: api-container
    command: /start
    volumes:
      - ./backend:/backend
      - static_volume:/backend/staticfiles
      - media_volume:/backend/mediafiles
    expose:
      - 8000
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - PG_HOST=postgres-db
      - PG_PORT=5432
    depends_on:
      - postgres-db
    networks:
      - splitzy # Use the correct network name

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    image: ${DOCKER_USER}/${IMAGE_NAME2}:latest
    container_name: frontend-multistage-container
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /usr/share/nginx/html
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    depends_on:
      - api
    networks:
      - splitzy

  postgres-db:
    image: postgres:15.0-alpine
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - splitzy

networks:
  splitzy:
    driver: bridge
volumes:
  postgres_data:
  static_volume:
  media_volume:


